import React,{useEffect,useState} from 'react';
import languages from '../../data/alert-languages.json';
import {LocationItem} from '../../types';
const BASE=(import.meta as any).env?.VITE_API_URL||'/api';
const input='w-full rounded-lg border border-slate-600 bg-slate-900 p-3 text-white';
export function WhatsAppSettings({locations}:{locations:LocationItem[]}){
 const [status,setStatus]=useState<any>(null),[recipients,setRecipients]=useState<any[]>([]),[deliveries,setDeliveries]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState(()=>sessionStorage.getItem('operations-token')||'');
 async function request(path:string,options:RequestInit={}){const r=await fetch(`${BASE}/whatsapp${path}`,{...options,headers:{'Content-Type':'application/json','X-Operations-Key':sessionStorage.getItem('operations-token')||'',...options.headers},signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:Array.isArray(data.detail)?data.detail.map((e:any)=>e.msg).join('; '):'Request failed');return data;}
 async function refresh(){setError('');try{setStatus(await request('/status'));if(sessionStorage.getItem('operations-token')){const [r,d]=await Promise.all([request('/recipients'),request('/deliveries')]);setRecipients(r);setDeliveries(d);}}catch(e:any){setError(e.message)}}
 useEffect(()=>{refresh()},[]);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setBusy(true);setError('');try{await request('/recipients',{method:'POST',body:JSON.stringify({...data,location_id:data.location_id||null,opted_in:data.opted_in==='on'})});form.reset();await refresh();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="rounded-xl border border-slate-700 bg-[#0c1527] p-4 sm:p-6 space-y-4 text-base"><h2 className="text-xl font-semibold">WhatsApp crisis alerts</h2><p>Send approved Twilio WhatsApp notifications to registered, opted-in recipients when an operational alert becomes HIGH or SEVERE. Demo and simulator alerts are excluded.</p>

 <div className="flex flex-wrap gap-2 items-end"><label className="grow">Deployment access key<input type="password" autoComplete="off" className={input} value={key} onChange={e=>setKey(e.target.value)}/></label><button className="rounded bg-blue-600 px-4 py-3" onClick={()=>{sessionStorage.setItem('operations-token',key);refresh()}}>Connect / refresh</button></div>
 {error&&<p role="alert" className="rounded border border-rose-700 p-3 text-rose-200">{error}</p>}
 <form onSubmit={add} className="space-y-3"><h3 className="font-semibold">Register recipient</h3><div className="grid sm:grid-cols-2 gap-3"><label>Name<input className={input} name="name" required minLength={2} maxLength={120}/></label><label>WhatsApp phone number<input className={input} name="phone" type="tel" placeholder="+919876543210" pattern="\+[1-9][0-9]{7,14}" required/></label></div><label className="block">Alert coverage<select className={input} name="location_id" aria-label="Alert coverage"><option value="">All monitored locations</option>{locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label><label className="block">Alert language<select className={input} name="language">{Object.entries(languages).map(([code,item])=><option key={code} value={code}>{item.name}{status?.languages?.[code]?.configured?'':' — template setup required'}</option>)}</select></label><label className="block">Consent record/reference<input className={input} name="consent_reference" placeholder="Signed registration form or WhatsApp opt-in reference" required minLength={5} maxLength={300}/></label><label className="flex gap-2"><input type="checkbox" name="opted_in" required/>This person explicitly agreed to receive WhatsApp crisis alerts.</label><button disabled={busy||!key} className="rounded bg-blue-600 px-4 py-3 disabled:opacity-50">{busy?'Saving…':'Add recipient'}</button></form>
 <div className="space-y-2"><h3 className="font-semibold">Registered recipients ({recipients.length})</h3>{recipients.map(r=><div key={r.id} className="flex flex-wrap justify-between gap-2 border-b border-slate-700 py-2"><span>{r.name} · {r.phone} · {r.location_id||'All locations'} · {(languages as any)[r.language||'en']?.name}</span><button className="text-rose-300" onClick={async()=>{if(!confirm(`Remove ${r.name} and cancel pending alerts?`))return;try{await request(`/recipients/${r.id}`,{method:'DELETE'});await refresh()}catch(e:any){setError(e.message)}}}>Remove / opt out</button></div>)}</div>
 <div className="space-y-2"><h3 className="font-semibold">Recent deliveries</h3><p className="text-sm text-slate-400">Queued or sent does not mean delivered. UNKNOWN means the outcome needs checking in Twilio; automatic resend is stopped to avoid duplicates.</p>{!deliveries.length&&<p>No deliveries recorded.</p>}{deliveries.map(d=><div key={d.id} className="border-b border-slate-700 py-2 break-words"><strong>{d.recipient_name} · {d.alert_id} · {d.severity} · {d.language||'en'} · {d.status}</strong><p className="text-sm">Attempts: {d.attempts} {d.twilio_sid&&`· ${d.twilio_sid}`}</p>{d.error&&<p className="text-amber-300 text-sm">{d.error}</p>}</div>)}</div></section>
}
